### ISSUE TITLE
I fixed most part of the Script, I want to become the mantainer.

### ISSUE THREAD

**Issue by pyro000** [1wsx10/VectorThrust2#16]
Hello, I tried to contact the author of this script in steam with no response, I fixed most bugs that had this script, now it is 100% playable in any environment and some quality of life improvements.
I want to become the mantainer and have your permission to post another workshop thread with the new script, because I'm still using most part of your code and I'm willing to use it in the future.
I hope I can reach you from here.
Have a nice day.

**Comment by 1wsx10** [comment]
Hi, thats great to hear. what did you fix?

**Comment by pyro000** [comment]
Pretty much I created a editable, performance free configuration in the custom data of the PB, you can combine thrusters of the same grid with nacelles and not receive miscalculations, you can brake in space with any nacelle without any problems, some performance and interface improvements, fixed the dampeners bugging out sometimes, a better tag assignation and I'm thinking about removing the standby, jetpack mode, and I even somehow fixed the buggy all axis nacelles that was impossible in some grids before. What do you think? You can test if you like. I only need your approbation.

Edit: I forgot to mention now it has multiple accelerations to toggle, 100% customizable, and most of the variables that you mentioned the player to modify are now in the custom data, pretty sure you don't need to run the script to change a variable.

[Here](https://gfycat.com/grotesquethunderousemperorpenguin) I have a demo gif.

Cheers.

**Comment by 1wsx10** [comment]
Sounds pretty good. you can upload your own version on the workshop or i can add you as a contributor to the current workshop page and this github. if you'd like the second then i'd ask you to also keep this github up to date with the version of the script on the workshop page.

I wouldn't remove standby mode if i were you. it's there to be nice to servers and SP players with large worlds. its not too nice having large scripts executing each frame nu-necessarily. if you can get the same functionality as standby by turning off the PB go for it. i don't remember but i think there was a reason i didn't do that at the time.

i had a couple reasons for jetpack.
A, if you are landing for a short period, you want your nacelles to keep pointing down. otherwise they may spin fast and slap into the ground when you power back up.
B, its a nice way to go directly down in a gravity well without large amounts of rotation on the nacelles.

that said, it was actually there instead of standby mode at first, you could mitigate A and B in other ways. it's just called jetpack because it's bound to the suit jetpack key in control module.

did you fix the solver? i never got that working perfectly unfortunately, but it works for a lot of designs.

a big killer for my motivation was KFT.. it really screws you over when it comes to a lot of designs and there isn't a whole lot the script can do about it.

**Comment by 1wsx10** [comment]
what do you mean by "performance free configuration"?

**Comment by pyro000** [comment]
Thank you so much, I'll fork this asap. 

> a big killer for my motivation was KFT.. it really screws you over when it comes to a lot of designs and there isn't a whole lot the script can do about it.

Yep, KFT still exists in some cases but it isn't that agressive anymore, you can pretty much put more nacelles in same axis but you definetly have to put a stronger nacelle in the middle of center of mass.

> what do you mean by "performance free configuration"?

I made a configuration in the custom data where it gathers all the configuration every X seconds, where that X is also customizable, you can change lowtrustcutoff/on, a multiplier variable I made, tags, etc.

Ah, I solved some of your TODOs btw, specially the nacelle grouping one by axis.
I'll notify you when I post everything, thank you again for your code too, I got so much inspired by this script that I decided to improve it.

Cheers

**Comment by 1wsx10** [comment]
ah, nice. so you have improved the solver.
ill take a look at your maths at some point then :)

**Comment by pyro000** [comment]
Hi, sorry for dissapearing this time, I had to add and fix some issues I had with the code, now it's done.

[This is the Workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=2831096030), I posted this, so you can add me and tell me if you need something.

And [this is the fork](https://github.com/pyro000/Vector-Thrust-OS), the new fixed version.

Cheers and thank you so much!
